version: "3.7"

services:

  # Camera streaming server
  camera:
    build: 
      context: ./
      dockerfile: camera.Dockerfile
    privileged: true
    network_mode: host

  control:
    build: 
      context: ./
      dockerfile: control.Dockerfile
    volumes: 
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true
    network_mode: host
    # ports:
    #   - "80:80"